# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160314_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
